# Generated by Django 5.2 on 2025-04-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_referraltender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referraltender',
            name='document',
            field=models.FileField(upload_to='referral_tenders/'),
        ),
    ]
