# Generated by Django 5.2 on 2025-04-29 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_collaborationrequest_requested_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='created_at',
        ),
        migrations.AddField(
            model_name='collaborationrequest',
            name='tender_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_collab_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
