# Generated by Django 5.2 on 2025-04-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_collaborationrequest_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='status',
        ),
    ]
